# Generated by Django 5.2.7 on 2025-10-31 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_sale_options_alter_sale_store'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
