# Generated by Django 5.2.7 on 2025-11-01 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_advertisement_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertisement',
            name='media_type',
            field=models.CharField(choices=[('image', 'Image'), ('video', 'Video')], default='image', max_length=10),
        ),
        migrations.AddField(
            model_name='advertisement',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='ads/videos/'),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='ads/images/'),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
