# Generated by Django 5.2.7 on 2025-11-02 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_staff_salarysettlement_attendance'),
    ]

    operations = [
        migrations.RenameField(
            model_name='staff',
            old_name='hourly_rate',
            new_name='daily_rate',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='check_in',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='check_out',
        ),
        migrations.RemoveField(
            model_name='salarysettlement',
            name='total_hours',
        ),
        migrations.AddField(
            model_name='salarysettlement',
            name='total_days',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
