# Generated by Django 5.2.7 on 2025-11-02 17:44

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_staff_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staff',
            name='join_date',
        ),
        migrations.RemoveField(
            model_name='staff',
            name='user',
        ),
        migrations.AddField(
            model_name='staff',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='staff',
            name='name',
            field=models.CharField(default='Unknown', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='staff',
            name='daily_rate',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
