# Generated by Django 5.2.7 on 2025-11-02 19:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_remove_staff_join_date_remove_staff_user_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='salarysettlement',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='salarysettlement',
            name='staff',
        ),
        migrations.DeleteModel(
            name='Attendance',
        ),
        migrations.DeleteModel(
            name='SalarySettlement',
        ),
        migrations.DeleteModel(
            name='Staff',
        ),
    ]
