# Generated by Django 5.2.7 on 2025-11-03 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_alter_salarysettlement_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='bio',
            field=models.TextField(blank=True, help_text='Short description or about section for the store', null=True),
        ),
        migrations.AddField(
            model_name='store',
            name='cover_image',
            field=models.ImageField(blank=True, help_text='Background banner for store profile', null=True, upload_to='stores/banners/'),
        ),
        migrations.AddField(
            model_name='store',
            name='logo',
            field=models.ImageField(blank=True, help_text='Store display picture (profile image)', null=True, upload_to='stores/logos/'),
        ),
    ]
