# Generated by Django 5.2.7 on 2025-11-03 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_store_bio_store_cover_image_store_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertisement',
            name='overlay_style',
            field=models.CharField(choices=[('light', 'Light'), ('dark', 'Dark')], default='dark', max_length=10),
        ),
        migrations.AddField(
            model_name='advertisement',
            name='text_position',
            field=models.CharField(choices=[('left', 'Left'), ('center', 'Center'), ('right', 'Right')], default='center', max_length=10),
        ),
    ]
