# Generated by Django 5.2.7 on 2025-11-03 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_advertisement_overlay_style_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisement',
            name='overlay_style',
            field=models.CharField(choices=[('light', 'Light – Soft white overlay for bright visuals'), ('dark', 'Dark – Subtle black overlay for luxury contrast'), ('golden', 'Golden – Warm amber tone for premium or festive themes'), ('rose', 'Rose – Gentle pink tint for lifestyle or fashion'), ('aqua', 'Aqua – Modern blue-green tint for tech or freshness'), ('smoke', 'Smoke – Muted gray haze for cinematic effect'), ('midnight', 'Midnight – Deep navy overlay for premium night themes'), ('emerald', 'Emerald – Rich green overlay for organic or nature-inspired content')], default='dark', max_length=10),
        ),
    ]
