# Generated by Django 5.2.7 on 2025-11-05 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_sale_credit_amount_sale_customer_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='invoice_no',
            field=models.CharField(blank=True, max_length=128, null=True, unique=True),
        ),
    ]
