# Generated by Django 5.2.7 on 2025-11-06 20:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_alter_sale_invoice_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='store',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='core.store'),
        ),
    ]
