# Generated by Django 5.2.7 on 2025-11-10 16:51

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_staff_salaryrecord_attendance'),
    ]

    operations = [
        migrations.CreateModel(
            name='BuyNowOrder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('customer_name', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=20)),
                ('address', models.TextField()),
                ('pincode', models.CharField(max_length=15)),
                ('landmark', models.CharField(blank=True, max_length=255, null=True)),
                ('district', models.CharField(max_length=100)),
                ('state', models.CharField(default='Kerala', max_length=100)),
                ('country', models.CharField(default='India', max_length=100)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('cancelled', 'Cancelled'), ('delivered', 'Delivered')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buy_now_orders', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buy_now_orders', to='core.product')),
                ('size', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.productsize')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buy_now_orders', to='core.store')),
            ],
        ),
    ]
