# Generated by Django 5.2.7 on 2025-12-03 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_remove_product_category_offercategory_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='storecategory',
            name='dp_image',
            field=models.ImageField(blank=True, null=True, upload_to='categories/dp/'),
        ),
        migrations.AddField(
            model_name='storesubcategory',
            name='dp_image',
            field=models.ImageField(blank=True, null=True, upload_to='subcategories/dp/'),
        ),
    ]
